### ISSUE TITLE
Composer install uptodate?

### ISSUE THREAD

**Issue by m-hume** [ifsnop/mysqldump-php#116]
Hi
I just installed using `composer require ifsnop/mysqldump-php:2.*`
and got `Installing ifsnop/mysqldump-php (v2.2)`

When i came to use `'reset-auto-increment' => true`
i got `mysqldump-php error: Unexpected value in dumpSettings: (reset-auto-increment)`

on examination of the code `reset-auto-increment` is missing from `$dumpSettingsDefault` in Mysqldump.php

Have i got a cached old version or do you need to commit something somewhere?
cheers

**Comment by ifsnop** [comment]
reset-auto-increment is available only in the master branch, but composer is still pointing to the v2.2 release (the latest release I did). Since reset-auto-increment (and foreign key check, virtual column support, support of mysql 5.7, event dump) introduces many modifications to the code, I wanted to give some time for testing (and bug reports).

Would you please test reset-auto-increment by updating to the last commit? If everything is ok, I will tag a new release.

Thanks in advance!

**Comment by m-hume** [comment]
Ah ok
That would explain the difference. I didn't realise `reset-auto-increment` was a new feature.
I can vouch for the script to be working with `reset-auto-increment` but i don't use foreign key checks, virtual columns, mysql 5.7 or events

Maybe a change log/version history would have helped?!
Thank you for sharing! 
It has made backing up my DB's easy as pie!
mh

**Comment by ifsnop** [comment]
I will update the changelog with the new release in a couple of hours. Meanwhile, everything is in the commit history 😇
