### ISSUE TITLE
GZIP Compression not working

### ISSUE THREAD

**Issue by koushik72** [ifsnop/mysqldump-php#119]
Hi, I have been using it lately and it works pretty awesomely apart from one thing. I am not able to use GZIP compression.
I am using it in my Laravel app.
Here is the code.
`$new = new Mysqldump('mysql:host=localhost;dbname=alerts', 'root', '');
    Mysqldump::GZIP;
    $new->start('dump.sql');`
I have also tried
`$new = new Mysqldump('mysql:host=localhost;dbname=alerts', 'root', '');
    $new::GZIP;
    $new->start('dump.sql');`

But it returns the same file size. I am confused on where I am doing wrong.
Please help. Thanks in advance.

**Comment by ifsnop** [comment]
As I see, the problem is with the call. You are supposed to define the compress option inside the settings array that is passed to the Mysqldump constructor. Please see a working example here:

https://github.com/ifsnop/mysqldump-php/wiki/Full-usage-example

and change 
~~~
'compress' => IMysqldump\Mysqldump::NONE,
~~~

with 

~~~
'compress' => IMysqldump\Mysqldump::GZIP,
~~~

Regards,
