### ISSUE TITLE
An extra 0 is added in table name

### ISSUE THREAD

**Issue by klausveliu** [ifsnop/mysqldump-php#124]
When I try to backup my database an extra 0 is generated in each table name.
CREATE TABLE `**0**users` (
  `id` int(11) NOT NULL AUTO_INCREMENT ...

`try {
	require_once(APP_RESOURCE_PATH . 'Mysqldump.php');
	$DBbackupFilename	= TMP_PATH . uniqid() . '.sql';
	$dump				= new Ifsnop\Mysqldump\Mysqldump('mysql:host=' . $DBHostname . ';dbname=' . $DBDatabase, $DBUsername, $DBPassword);
	$dump->start($backupFilename);
	$error_code			= 0;
	$description		= $backupFilename;
} catch (\Exception $exception) {
	$error_code			= 1;
	$description		= $exception->getMessage();
}`
Is this a bug or I am doing something wrong?

**Comment by ifsnop** [comment]
When I try to backup my database an extra 0 is generated in each table name.
CREATE TABLE **0**users (
id int(11) NOT NULL AUTO_INCREMENT ...

try { require_once(APP_RESOURCE_PATH . 'Mysqldump.php'); $DBbackupFilename
= TMP_PATH . uniqid() . '.sql'; $dump = new
Ifsnop\Mysqldump\Mysqldump('mysql:host='
. $DBHostname . ';dbname=' . $DBDatabase, $DBUsername, $DBPassword);
$dump->start($backupFilename); $error_code = 0; $description =
$backupFilename; } catch (\Exception $exception) { $error_code = 1;
$description = $exception->getMessage(); }
Is this a bug or I am doing something wrong?


I don't see any obvious error. Since current version is running all tests
correctly, could you please provide a small dump where I could reproduce
the problem using mysqldump and current mysqldump-php?

Thanks!

**Comment by klausveliu** [comment]
After checking the next day I see that I having some old tables with that index(0), also I noticed some other issue with my tables while seeing the exported sql.
Conclusion: The fault was not in mysqldump-php part.
Thank you for your time!
