### ISSUE TITLE
Commercial License?

### ISSUE THREAD

**Issue by mattsimpson** [ifsnop/mysqldump-php#132]
Hello @ifsnop, I was wondering if it is possible for us to procure a commercial license of the `mysqldump-php` library? We are currently using it in an GPL'd project, but we are investigating a possible license shift to a community source license (vs. open source). I am studying the impact of this shift, and what it would mean license-wise.

Sincerely,
Matt Simpson

**Comment by ifsnop** [comment]
Hi @mattsimpson,

I am very glad to know that mysqldump-php is useful for your organisation.  Currently, mysqldump-php is GPLv3.0, and changing our license would require the agreement of all the other contributors. Giving a commercial license to your organisation would mean that your contributions would be lost. Mysqldmp-php is so useful because of other people contributions. Since I really care about sharing improvements, as they help to make better software, I don't think giving commercial licenses is a good idea.

Regards,
Diego

**Comment by roeycohen** [comment]
hi @ifsnop, could you consider changing the license to LGPL?

I understand the need to keep the project updated, but GPLv3 can also prevent it from being updated if someone needs to embed it inside a bigger commercial project.
In that case, he wouldn't use it in the first place... 

so LGPL seems more correct for this project.

**Comment by ifsnop** [comment]
Sorry, but as I commented previously I think GPL2/3 will benefit the community, whereas LGPL/MIT/BSD type will benefit companies/commercial projects. If someone needs to include mysqldump-php, it can always be downloaded before installation, for example.

**Comment by ifsnop** [comment]
That a BSD/MIT type license don't enforce them to share the improvements.

Regards,

**Comment by roeycohen** [comment]
That's why i've suggest LGPL (which isn't like BSD/MIT):
If one modifies the licensed code, he must release the modified portions under the LGPL (without releasing stuff out side the library).
