### ISSUE TITLE
Sqlite: missing host

### ISSUE THREAD

**Issue by geek-merlin** [ifsnop/mysqldump-php#135]
When i try to dump a sqlite db, i get
```
In Mysqldump.php line 251:                               
  Missing host from DSN string  
``` 
although the host is not needed for sqlite.

**Comment by ifsnop** [comment]
I suspect that sqlite support was broken some time ago since it is not
automatically tested, and I no longer use any sqlite database. Surely only
some minor fixes are needed to move some code to the typeadapter class.

Any PR will be very welcomed.

--
-- Madrid / Spain

El 7 abr. 2018 4:31 a. m., "axel-rutz" <notifications@github.com> escribió:

When i try to process a sqlite file, i get

In Mysqldump.php line 251:
  Missing host from DSN string

although the host is not needed for sqlite.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ifsnop/mysqldump-php/issues/135>, or mute the thread

**Comment by Entomologen** [comment]
I had a similar issue with MariaDB. It turned out I had to put a port number into the DSN string for the connection to work. In my case:
>	$dsn = 'mysql:host=localhost;port=3306;dbname=' . DataBase::NAME;
>	$dump = new MySqlDump($dsn , DataBase::NAME , DataBase::PASS);

**Comment by bradjones1** [comment]
Basically sqlite is only supported in theory - I am implementing some local integration testing for an internal project and started in on this to at least get data out. I don't think it would be particularly difficult to make this fully compatible. https://github.com/ifsnop/mysqldump-php/pull/184

**Comment by ifsnop** [comment]
This is fantastic! I used mysqldump-php long ago for also dumping sqlite databases, but haven't had the time to sync it with all the changes that were done to the mysql part.

**Comment by ifsnop** [comment]
Closing until a PR is made. Waiting for it to happen.

**Comment by bradjones1** [comment]
I'm no longer on the project where this was being used so I haven't returned to this.
