### ISSUE TITLE
Expose $tableColumnTypes

### ISSUE THREAD

**Issue by axel-rutz** [ifsnop/mysqldump-php#136]
Hi there, i'm using this awesome library in https://github.com/machbarmacher/gdpr-dump to
a) build a shell command via symfony console
b) override getColumnStmt() to obfuscate some columns

To get column info i'd need $tableColumnTypes exposed and will add a PR wit a getter.

**Comment by axel-rutz** [comment]
Also note that if my project - as i hope - gets some traction you might get a flood of issues and PRs. Just as warning ;-).

**Comment by ifsnop** [comment]
Using a getter may not be very useful, because it will be difficult to call it when executing (since only start() is called and is a do-everything method).

I think using hooks could be an easier solution. Extending mysqldump class and adding your custom method instead of an empty hook may get you work done. Please see commit 5773960a0a9b9ba80daae2458de77dde48dec54e.

**Comment by ifsnop** [comment]
This is another option to add some callbacks to current code:

https://github.com/AwardWallet/mysqldump-php/commit/d5cd69471599c47feaffbfc02c5a625290cbf258

**Comment by bomoko** [comment]
I'm happy to take a swing at this via one of the other routes suggested above.

**Comment by bomoko** [comment]
Hi All

So #141 is a proposal to address the issue @axel-rutz is having above.

specifically, it allows us to transform something like

```
  public function getColumnStmt($tableName) {
    $columnStmt = parent::getColumnStmt($tableName);
    $columnTypes = $this->tableColumnTypes()[$tableName];
    foreach (array_keys($columnTypes) as $i => $columnName) {
      if (!empty($this->gdprExpressions[$tableName][$columnName])) {
        $expression = $this->gdprExpressions[$tableName][$columnName];
      }
    }
    if ($this->debugSql) {
      print "/* SELECT " . implode(",", $columnStmt) . " FROM `$tableName` */\n\n";
    }
    return $columnStmt;
  }
```
into something like
```
  public function hookTransformColumnStmt($tableName, $columnName, $colType) {
    if (!empty($this->gdprExpressions[$tableName][$columnName])) {
      $expression = $this->gdprExpressions[$tableName][$columnName];
      return "$expression as $columnName";
    }
    return FALSE;
  }

```

**Comment by ifsnop** [comment]
Implemented in #141

**Comment by bomoko** [comment]
Hi @ifsnop 

Sorry to be a bother, I just want to understand why this (and the PR #141) was closed, since I'm not following the references between tickets and PRs.

Above you say that this was implemented in #141 - which is true. But then you closed that PR with by saying that it was implemented in the PR #139.

There is a kind of overlap in functionality in 141 and 139, absolutely. The big difference is that 141 allows manipulation of the expression before it's run, while 139 allows the data to be manipulated _after_ the fact. Perhaps the two functions are so similar to make them functionally equivalent from mysqldump-php's perspective. Is that why you've closed 141 with 139?

**Comment by ifsnop** [comment]
Probably my mistake. I have considered them to be overlaped, and #139 cleaner than #141.

Why? Because #141 had several conceptual issues.

Just to clarify: getColumnStmt is used to generate the select part of the query that gets the values from the actual db. Not the data, but the column names. You are proposing to use the hook to make changes, using the sql query. (for example, encrypt values from a column when extracting them from the db).

So, the proposed change:

~~~
if($hookColumnStmt = $this->hookTransformColumnStmt($tableName, $colName, $colType)) {
    $colStmt[] = $hookColumnStmt;
} else if ($colType['type'] == 'bit' && $this->dumpSettings['hex-blob']) {
                 $colStmt[] = "LPAD(HEX(`${colName}`),2,'0') AS `${colName}`";
~~~
If you call hookTransform... and return true, then hex-blob or bit columns won't be parsed correclty.

The hook should be called for every column. But after calling it, there is no easy way to check for blob/hex/virtual columns, since they have been changed.

I'm not sure if I have expressed my concerns. What do you think?

**Comment by bomoko** [comment]
Hi @ifsnop 

Thanks so much for the reply.

The concerns are definitely warranted. And, in fact, were similar to my own concerns with it when I was trying to implement your suggestion of using hooks for _this_ requirement. I think you're spot on.

For background, the code that the OP is using this for actually _does_ manipulate the SQL.
It was being used to do replacements to the data by, say, replacing column names with SQL expressions. And, in fact, it works pretty nicely (there's a patch that we're using in the gdpr-dump project that adds the proposed getter above).

For the record, the more I work with the overridden version of the code, the more I think that some mechanism for exposing the column meta-data (along the lines that Axel proposed above) would be useful. For instance, I'm imagining an overridden version of this where we use the meta-data to generate extreme test data - strings that are the maximum length that a column can store etc. for testing interfaces. We could use the meta-data to generate these extreme data.

I would love to chat about this further to see what kind of solution would work.
