### ISSUE TITLE
NFR: PHP 7.2 / Strict Typing / Class Per-File

### ISSUE THREAD

**Issue by Niko9911** [ifsnop/mysqldump-php#142]
Hey, would any of these options make sense?

- PHP 7.2 
- Strict Typing 
- Class Per-File
- Better Namespacing

I'm willing to make PR if agreed.

**Comment by ifsnop** [comment]
> Hey, would any of these options make sense?
>
>    - PHP 7.2
>
> Where do you suggest using 7.2? In Travis configuration?


>    - Strict Typing
>
> This could be a good thing.


>    - Class Per-File
>
> No, I want to be able to deploy uploading a self contained file.


>    - Better Namespacing
>
> Please propose.


>
> I'm willing to make PR if agreed
>

Before doing massive changes, could you make some examples?

Thanks for your time.

>

**Comment by Niko9911** [comment]
Will be dropping too much stuff, so I will create new total version with different name of package. Only 20% of original code will be preserved. 

If interested about other version, please see my profile. I cannot make fork due I'm using mirror on GitHub and making development on my private git instance.

**Comment by ifsnop** [comment]
Good idea, thank you for contributing to free software. Just remember to follow GPL.

**Comment by zfmaster** [comment]
Hi, @ifsnop 

> No, I want to be able to deploy uploading a self contained file.

Are you still deploying with uploading self-contained file? It's very hard to to any investigations of sources when everything is located in one file. In the end of the day you could use phar, or composer, or even add some hooks which will automatically build single-file version on each update.  

@Niko9911 did a good job in his repo, but it's not developed since 2018.

**Comment by Niko9911** [comment]
I have no use for this anymore, due using native implementation. However, I can help, if there is need for it.

Would recommend to check phar. I can setup phar building into my Repo, if there is interest for it.

**Comment by ifsnop** [comment]
Phar is a very good way to create an unique file. With this in mind, I have also considered to split source in several files. But would like to retain compatibility with php versions as older as possible (php 5.3), so no fancy array definitions using [], for example. So yes, I will accept PR.

@Niko9911 dropped the support of several things that I think are still useful (for example, php versions older that 7.0) and instead of creating a fork, he uploaded a new project. I don't like what he did, but, this is his understanding of open source. In the other hand, sqlite is no longer maintained, and I believe that there have never been a true interest in it, so code could be simplified.

**Comment by Niko9911** [comment]
I highly disagree. Anything bellow 7.2 should be considered as unsupported. If ppl want keep their support for 5.3, they can stay in "legacy" version.

PHP 7.1 is already EOL and latest supported is 7.2.

Im not interested about doing a full refractor, which would require a lot of time. Instead of that, I will rather put that work into my fork. Previous statement having support also to 5.3 highly is supporting me continue with my fork instead of refactoring this.

Just as note, new repo was created due having problems on fork at Github end at time of doing that.

**Comment by zfmaster** [comment]
@ifsnop , @Niko9911 , I think this question is more strategical. The number of people using php older than 7.0 is less than 10% (https://blog.packagist.com/php-versions-stats-2019-1-edition/), and biggest part of this users are on it because companies they develop for just do not provide budget for refactor applications to newer version. But also we should consider what biggest part of developers who still have outdated applications have workarounds like few different php versions installed on servers. 

I suggest to make people vote with downloads. There could be created legacy branch, which will support php 5.3, like now and main branch which will require php 7.2. The main branch could be updated to PSR standards and get PR for new functionalities and legacy branch could still accept PR for bugfixes and PRs if somebody from outdated php version users will want to port new functionality from main branch (really do not think there will be lot of them).

**Comment by Niko9911** [comment]
Closing as unproductive.
