### ISSUE TITLE
Needs SUPER privilege for operation

### ISSUE THREAD

**Issue by selahattinalan** [ifsnop/mysqldump-php#54]
Solved

**Comment by TimGS** [comment]
I think the single-transaction switch only requires the SUPER privilege for the SET GLOBAL statement in TypeAdapterMysql::start_transaction().

As this SET GLOBAL statement will often be superfluous to requirements as the default level is REPEATABLE READ anyway, can we have an option in this script to switch off this call? That way those of us running this script on shared hosts (probably most of us) can have a transaction-safe dump

thanks,
-- Tim.

**Comment by ifsnop** [comment]
Let me recall some facts about this: I don't like the idea of having a switch from mysqldump-php named as one from mysqldump that does a different thing.

http://dev.mysql.com/doc/refman/5.0/en/mysqldump.html#option_mysqldump_single-transactiion

As you said, single-transaction includes the following when reading from the server:

~~~
SET GLOBAL TRANSACTION ISOLATION LEVEL REPEATABLE READ;
START TRANSACTION;
[...]
COMMIT;
~~~

I think about several options:

1) Replace SET GLOBAL with SET SESSION:

With the SESSION keyword, the statement sets the default transaction level for all subsequent transactions performed within the current session.

A change to the global default isolation level requires the SUPER privilege. Any session is free to change its session isolation level (even in the middle of a transaction), or the isolation level for its next transaction. 

Will it cause the same effect replacing GLOBAL with SESSION?

2) Remove "SET GLOBAL TRANSACTION ISOLATION LEVEL REPEATABLE READ;" completely, since this is the default option in the server.
I think this is a bad idea.

3) Separate "SET GLOBAL..." from START TRANSACTION, as per you suggestion.

What do you think?

**Comment by TimGS** [comment]
Replacing SET GLOBAL with SET SESSION seems reasonable. I can't test it on the computer I'm currently on, but I can't see any problems - AFAIK SET SESSION does need any special privileges.

-- Tim.

**Comment by ifsnop** [comment]
I'm not use about the usage of SET SESSION against SET GLOBAL.A dump should guarantee that the dabatase is in a consistent state. SET SESSION only protects against modifications in the same session, so someone in another session could modify the database during a dump.

Maybe is better to check the status of the transaction level, and don't change it if it is GLOBAL with REPEATEBLE READ. Only change if it is needed.Maybe a PR could improve things :smile:

**Comment by TimGS** [comment]
I may be wrong - but doesn't SET SESSION guarantee a consistent dump?

Someone _else_ may well have a session with a different transaction isolation level but SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ should guarantee that *this* session gets the snapshot set by the first read in the transacion.

http://dev.mysql.com/doc/refman/5.0/en/set-transaction.html

"All consistent reads within the same transaction read the snapshot established by the first read."

Someone _else_ in a different session may well modify the database during the transaction, but these modifications will not be reflected in our session - we still get the snapshot set by the first read.

-- Tim.

**Comment by ifsnop** [comment]
Ok, I have understood where my mistake was. I will change global to session and it should work exactly the same.

**Comment by TimGS** [comment]
OK. Thanks.
-- Tim.

**Comment by ifsnop** [comment]
Thanks to you for taking the time to report this issue.
