### ISSUE TITLE
Getting output in variable

### ISSUE THREAD

**Issue by traBolic** [ifsnop/mysqldump-php#77]
Hi, can i get mysqldump output in a variable?
I found a tricky way to do that but is there any simple/quick way to do this?

    include_once(dirname(__FILE__) . '/mysqldump-php-1.4.1/src/Ifsnop/Mysqldump/Mysqldump.php');
    $dump = new Ifsnop\Mysqldump\Mysqldump( 'database', 'username', 'password');
    
    ob_start();
    $dump->start('php://output');
    $output = ob_get_contents();
    ob_end_clean();

**Comment by tomsommer** [comment]
+1

**Comment by ifsnop** [comment]
Of course,  I totally agree with you.  I currently don't have much free time,  so PR are wellcomed.

**Comment by sul4bh** [comment]
Has this already been implemented? I see this in devel:
https://github.com/ifsnop/mysqldump-php/blob/devel/src/Ifsnop/Mysqldump/Mysqldump.php#L67

I also read this: https://github.com/ifsnop/mysqldump-php/issues/83#issuecomment-122413932

Are you waiting on #77 and #61 to be implemented for 1.7? I am interested to work on them.

**Comment by ifsnop** [comment]
I have made some big changes in the devel version. It is going to be named
2.0, since it will break some default behaviour (ie. the default output
filename as you pointed out). More important is that now we parse the same
dsn string as PDO, so you could change the mysql port, bind to a socket,
etc. But this dsn is not backwards compatible.

I will merge with devel into 2.0 once I  check the bug report from #88 (in
a week or so).

**Comment by ybelenko** [comment]
So... still cannot find an option to write output into variable? Is it possible in 2.9 version?
